# Generated by Django 2.0.13 on 2019-05-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=75)),
                ('text', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('no_reacts', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(default='', unique=True)),
                ('author', models.CharField(max_length=75)),
                ('author_url', models.URLField()),
                ('description', models.TextField()),
                ('total_reacts', models.CharField(max_length=10)),
                ('likes', models.CharField(max_length=10)),
                ('heart', models.CharField(max_length=10)),
                ('wow', models.CharField(max_length=10)),
                ('haha', models.CharField(max_length=10)),
                ('sad', models.CharField(max_length=10)),
                ('angry', models.CharField(max_length=10)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.FacebookGroup')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.Post'),
        ),
    ]
