# Generated by Django 2.0.13 on 2019-05-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190509_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
