# Generated by Django 2.0.13 on 2019-05-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190509_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
