# Generated by Django 2.0.13 on 2019-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190509_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_url',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='', unique=True),
        ),
    ]
